-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spike_binder_reduced]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace spike_binder_reduced

/-- [core::mem::size_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 373:0-373:34
    Name pattern: [core::mem::size_of]
    Visibility: public -/
@[rust_fun "core::mem::size_of"]
axiom core.mem.size_of (T : Type) : Result Std.Usize

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [spike_binder_reduced::Error]
    Source: 'src/lib.rs', lines 23:0-23:26
    Visibility: public -/
@[reducible]
def Error := Std.I32

/-- [spike_binder_reduced::{impl core::fmt::Debug for spike_binder_reduced::Error}::fmt]:
    Source: 'src/lib.rs', lines 22:9-22:14
    Visibility: public -/
def Error.Insts.CoreFmtDebug.fmt
  (self : Error) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Error") dyn

/-- Trait implementation: [spike_binder_reduced::{impl core::fmt::Debug for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:9-22:14 -/
@[reducible]
def Error.Insts.CoreFmtDebug : core.fmt.Debug Error := {
  fmt := Error.Insts.CoreFmtDebug.fmt
}

/-- [spike_binder_reduced::{impl core::clone::Clone for spike_binder_reduced::Error}::clone]:
    Source: 'src/lib.rs', lines 22:16-22:21
    Visibility: public -/
def Error.Insts.CoreCloneClone.clone (self : Error) : Result Error := do
  ok self

/-- Trait implementation: [spike_binder_reduced::{impl core::clone::Clone for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:16-22:21 -/
@[reducible]
def Error.Insts.CoreCloneClone : core.clone.Clone Error := {
  clone := Error.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::{impl core::marker::Copy for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:23-22:27 -/
@[reducible]
def Error.Insts.CoreMarkerCopy : core.marker.Copy Error := {
  cloneInst := Error.Insts.CoreCloneClone
}

/-- Trait implementation: [spike_binder_reduced::{impl core::marker::StructuralPartialEq for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:29-22:38 -/
@[reducible]
def Error.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Error := {
}

/-- [spike_binder_reduced::{impl core::cmp::PartialEq<spike_binder_reduced::Error> for spike_binder_reduced::Error}::eq]:
    Source: 'src/lib.rs', lines 22:29-22:38
    Visibility: public -/
def Error.Insts.CoreCmpPartialEqError.eq
  (self : Error) (other : Error) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [spike_binder_reduced::{impl core::cmp::PartialEq<spike_binder_reduced::Error> for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:29-22:38 -/
@[reducible]
def Error.Insts.CoreCmpPartialEqError : core.cmp.PartialEq Error Error := {
  eq := Error.Insts.CoreCmpPartialEqError.eq
}

/-- [spike_binder_reduced::{impl core::cmp::Eq for spike_binder_reduced::Error}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 22:40-22:42
    Visibility: public -/
def Error.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Error) : Result Unit := do
  ok ()

/-- Trait implementation: [spike_binder_reduced::{impl core::cmp::Eq for spike_binder_reduced::Error}]
    Source: 'src/lib.rs', lines 22:40-22:42 -/
@[reducible]
def Error.Insts.CoreCmpEq : core.cmp.Eq Error := {
  partialEqInst := Error.Insts.CoreCmpPartialEqError
  assert_fields_are_eq := Error.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [spike_binder_reduced::EINVAL]
    Source: 'src/lib.rs', lines 24:0-24:36
    Visibility: public -/
@[global_simps, irreducible] def EINVAL : Error := 22#i32

/-- [spike_binder_reduced::uapi::binder_object_header]
    Source: 'src/lib.rs', lines 36:4-38:5
    Visibility: public -/
structure uapi.binder_object_header where
  type_ : Std.U32

/-- [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_object_header}::clone]:
    Source: 'src/lib.rs', lines 35:19-35:24
    Visibility: public -/
def uapi.binder_object_header.Insts.CoreCloneClone.clone
  (self : uapi.binder_object_header) : Result uapi.binder_object_header := do
  ok self

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_object_header}]
    Source: 'src/lib.rs', lines 35:19-35:24 -/
@[reducible]
def uapi.binder_object_header.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_object_header := {
  clone := uapi.binder_object_header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::marker::Copy for spike_binder_reduced::uapi::binder_object_header}]
    Source: 'src/lib.rs', lines 35:13-35:17 -/
@[reducible]
def uapi.binder_object_header.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_object_header := {
  cloneInst := uapi.binder_object_header.Insts.CoreCloneClone
}

/-- [spike_binder_reduced::uapi::flat_binder_object]
    Source: 'src/lib.rs', lines 42:4-47:5
    Visibility: public -/
structure uapi.flat_binder_object where
  hdr : uapi.binder_object_header
  flags : Std.U32
  __bindgen_anon_1 : Std.U64
  cookie : Std.U64

/-- [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::flat_binder_object}::clone]:
    Source: 'src/lib.rs', lines 41:19-41:24
    Visibility: public -/
def uapi.flat_binder_object.Insts.CoreCloneClone.clone
  (self : uapi.flat_binder_object) : Result uapi.flat_binder_object := do
  ok self

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::flat_binder_object}]
    Source: 'src/lib.rs', lines 41:19-41:24 -/
@[reducible]
def uapi.flat_binder_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.flat_binder_object := {
  clone := uapi.flat_binder_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::marker::Copy for spike_binder_reduced::uapi::flat_binder_object}]
    Source: 'src/lib.rs', lines 41:13-41:17 -/
@[reducible]
def uapi.flat_binder_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.flat_binder_object := {
  cloneInst := uapi.flat_binder_object.Insts.CoreCloneClone
}

/-- [spike_binder_reduced::uapi::binder_fd_object]
    Source: 'src/lib.rs', lines 51:4-56:5
    Visibility: public -/
structure uapi.binder_fd_object where
  hdr : uapi.binder_object_header
  pad_flags : Std.U32
  __bindgen_anon_1 : Std.U64
  cookie : Std.U64

/-- [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_fd_object}::clone]:
    Source: 'src/lib.rs', lines 50:19-50:24
    Visibility: public -/
def uapi.binder_fd_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_fd_object) : Result uapi.binder_fd_object := do
  ok self

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_fd_object}]
    Source: 'src/lib.rs', lines 50:19-50:24 -/
@[reducible]
def uapi.binder_fd_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_fd_object := {
  clone := uapi.binder_fd_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::marker::Copy for spike_binder_reduced::uapi::binder_fd_object}]
    Source: 'src/lib.rs', lines 50:13-50:17 -/
@[reducible]
def uapi.binder_fd_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_fd_object := {
  cloneInst := uapi.binder_fd_object.Insts.CoreCloneClone
}

/-- [spike_binder_reduced::uapi::binder_buffer_object]
    Source: 'src/lib.rs', lines 60:4-67:5
    Visibility: public -/
structure uapi.binder_buffer_object where
  hdr : uapi.binder_object_header
  flags : Std.U32
  buffer : Std.U64
  length : Std.U64
  parent : Std.U64
  parent_offset : Std.U64

/-- [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_buffer_object}::clone]:
    Source: 'src/lib.rs', lines 59:19-59:24
    Visibility: public -/
def uapi.binder_buffer_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_buffer_object) : Result uapi.binder_buffer_object := do
  ok self

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_buffer_object}]
    Source: 'src/lib.rs', lines 59:19-59:24 -/
@[reducible]
def uapi.binder_buffer_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_buffer_object := {
  clone := uapi.binder_buffer_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::marker::Copy for spike_binder_reduced::uapi::binder_buffer_object}]
    Source: 'src/lib.rs', lines 59:13-59:17 -/
@[reducible]
def uapi.binder_buffer_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_buffer_object := {
  cloneInst := uapi.binder_buffer_object.Insts.CoreCloneClone
}

/-- [spike_binder_reduced::uapi::binder_fd_array_object]
    Source: 'src/lib.rs', lines 71:4-77:5
    Visibility: public -/
structure uapi.binder_fd_array_object where
  hdr : uapi.binder_object_header
  pad : Std.U32
  num_fds : Std.U64
  parent : Std.U64
  parent_offset : Std.U64

/-- [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_fd_array_object}::clone]:
    Source: 'src/lib.rs', lines 70:19-70:24
    Visibility: public -/
def uapi.binder_fd_array_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_fd_array_object) :
  Result uapi.binder_fd_array_object
  := do
  ok self

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::clone::Clone for spike_binder_reduced::uapi::binder_fd_array_object}]
    Source: 'src/lib.rs', lines 70:19-70:24 -/
@[reducible]
def uapi.binder_fd_array_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_fd_array_object := {
  clone := uapi.binder_fd_array_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_reduced::uapi::{impl core::marker::Copy for spike_binder_reduced::uapi::binder_fd_array_object}]
    Source: 'src/lib.rs', lines 70:13-70:17 -/
@[reducible]
def uapi.binder_fd_array_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_fd_array_object := {
  cloneInst := uapi.binder_fd_array_object.Insts.CoreCloneClone
}

/-- [spike_binder_reduced::BINDER_TYPE_BINDER]
    Source: 'src/lib.rs', lines 81:0-81:47
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_BINDER : Std.U32 := 1935813253#u32

/-- [spike_binder_reduced::BINDER_TYPE_WEAK_BINDER]
    Source: 'src/lib.rs', lines 82:0-82:52
    Visibility: public -/
@[global_simps, irreducible]
def BINDER_TYPE_WEAK_BINDER : Std.U32 := 2002922117#u32

/-- [spike_binder_reduced::BINDER_TYPE_HANDLE]
    Source: 'src/lib.rs', lines 83:0-83:47
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_HANDLE : Std.U32 := 1936206469#u32

/-- [spike_binder_reduced::BINDER_TYPE_WEAK_HANDLE]
    Source: 'src/lib.rs', lines 84:0-84:52
    Visibility: public -/
@[global_simps, irreducible]
def BINDER_TYPE_WEAK_HANDLE : Std.U32 := 2003315333#u32

/-- [spike_binder_reduced::BINDER_TYPE_FD]
    Source: 'src/lib.rs', lines 85:0-85:43
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_FD : Std.U32 := 1717840517#u32

/-- [spike_binder_reduced::BINDER_TYPE_FDA]
    Source: 'src/lib.rs', lines 86:0-86:44
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_FDA : Std.U32 := 1717854597#u32

/-- [spike_binder_reduced::BINDER_TYPE_PTR]
    Source: 'src/lib.rs', lines 87:0-87:44
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_PTR : Std.U32 := 1886661253#u32

/-- [spike_binder_reduced::type_to_size]:
    Source: 'src/lib.rs', lines 92:0-103:1
    Visibility: public -/
def type_to_size (type_ : Std.U32) : Result (Option Std.Usize) := do
  match type_ with
  | 2002922117#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1935813253#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 2003315333#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1936206469#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1717840517#uscalar =>
    let i ← core.mem.size_of uapi.binder_fd_object
    ok (some i)
  | 1886661253#uscalar =>
    let i ← core.mem.size_of uapi.binder_buffer_object
    ok (some i)
  | 1717854597#uscalar =>
    let i ← core.mem.size_of uapi.binder_fd_array_object
    ok (some i)
  | _ => ok none

/-- [spike_binder_reduced::ptr_align]:
    Source: 'src/lib.rs', lines 106:0-109:1
    Visibility: public -/
def ptr_align (value : Std.Usize) : Result (Option Std.Usize) := do
  let i ← core.mem.size_of Std.Usize
  let size ← i - 1#usize
  let o ← lift (Usize.checked_add value size)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i1 ← lift (~~~ size)
    let i2 ← lift (val &&& i1)
    ok (some i2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.Usize residual

/-- [spike_binder_reduced::is_aligned]:
    Source: 'src/lib.rs', lines 111:0-113:1
    Visibility: public -/
def is_aligned (value : Std.Usize) (to1 : Std.Usize) : Result Bool := do
  let i ← value % to1
  ok (i = 0#usize)

/-- [spike_binder_reduced::size_check]:
    Source: 'src/lib.rs', lines 115:0-122:1
    Visibility: public -/
def size_check
  (offset : Std.Usize) (size : Std.Usize) (buffer_size : Std.Usize) :
  Result (core.result.Result Unit Error)
  := do
  let o ← lift (Usize.checked_add offset size)
  let overflow_fail := core.option.Option.is_none o
  let i ← lift (core.num.Usize.wrapping_add offset size)
  if overflow_fail
  then ok (core.result.Result.Err EINVAL)
  else
    if i > buffer_size
    then ok (core.result.Result.Err EINVAL)
    else ok (core.result.Result.Ok ())

end spike_binder_reduced
