-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spike_binder_remodel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace spike_binder_remodel

/-- [core::mem::size_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 373:0-373:34
    Name pattern: [core::mem::size_of]
    Visibility: public -/
@[rust_fun "core::mem::size_of"]
axiom core.mem.size_of (T : Type) : Result Std.Usize

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [spike_binder_remodel::Error]
    Source: 'src/lib.rs', lines 26:0-26:26
    Visibility: public -/
@[reducible]
def Error := Std.I32

/-- [spike_binder_remodel::{impl core::fmt::Debug for spike_binder_remodel::Error}::fmt]:
    Source: 'src/lib.rs', lines 25:9-25:14
    Visibility: public -/
def Error.Insts.CoreFmtDebug.fmt
  (self : Error) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugI32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Error") dyn

/-- Trait implementation: [spike_binder_remodel::{impl core::fmt::Debug for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:9-25:14 -/
@[reducible]
def Error.Insts.CoreFmtDebug : core.fmt.Debug Error := {
  fmt := Error.Insts.CoreFmtDebug.fmt
}

/-- [spike_binder_remodel::{impl core::clone::Clone for spike_binder_remodel::Error}::clone]:
    Source: 'src/lib.rs', lines 25:16-25:21
    Visibility: public -/
def Error.Insts.CoreCloneClone.clone (self : Error) : Result Error := do
  ok self

/-- Trait implementation: [spike_binder_remodel::{impl core::clone::Clone for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:16-25:21 -/
@[reducible]
def Error.Insts.CoreCloneClone : core.clone.Clone Error := {
  clone := Error.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::{impl core::marker::Copy for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:23-25:27 -/
@[reducible]
def Error.Insts.CoreMarkerCopy : core.marker.Copy Error := {
  cloneInst := Error.Insts.CoreCloneClone
}

/-- Trait implementation: [spike_binder_remodel::{impl core::marker::StructuralPartialEq for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:29-25:38 -/
@[reducible]
def Error.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Error := {
}

/-- [spike_binder_remodel::{impl core::cmp::PartialEq<spike_binder_remodel::Error> for spike_binder_remodel::Error}::eq]:
    Source: 'src/lib.rs', lines 25:29-25:38
    Visibility: public -/
def Error.Insts.CoreCmpPartialEqError.eq
  (self : Error) (other : Error) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [spike_binder_remodel::{impl core::cmp::PartialEq<spike_binder_remodel::Error> for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:29-25:38 -/
@[reducible]
def Error.Insts.CoreCmpPartialEqError : core.cmp.PartialEq Error Error := {
  eq := Error.Insts.CoreCmpPartialEqError.eq
}

/-- [spike_binder_remodel::{impl core::cmp::Eq for spike_binder_remodel::Error}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 25:40-25:42
    Visibility: public -/
def Error.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Error) : Result Unit := do
  ok ()

/-- Trait implementation: [spike_binder_remodel::{impl core::cmp::Eq for spike_binder_remodel::Error}]
    Source: 'src/lib.rs', lines 25:40-25:42 -/
@[reducible]
def Error.Insts.CoreCmpEq : core.cmp.Eq Error := {
  partialEqInst := Error.Insts.CoreCmpPartialEqError
  assert_fields_are_eq := Error.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [spike_binder_remodel::EINVAL]
    Source: 'src/lib.rs', lines 27:0-27:36
    Visibility: public -/
@[global_simps, irreducible] def EINVAL : Error := 22#i32

/-- [spike_binder_remodel::ENOMEM]
    Source: 'src/lib.rs', lines 28:0-28:36
    Visibility: public -/
@[global_simps, irreducible] def ENOMEM : Error := 12#i32

/-- [spike_binder_remodel::uapi::binder_object_header]
    Source: 'src/lib.rs', lines 43:4-45:5
    Visibility: public -/
structure uapi.binder_object_header where
  type_ : Std.U32

/-- [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_object_header}::clone]:
    Source: 'src/lib.rs', lines 42:19-42:24
    Visibility: public -/
def uapi.binder_object_header.Insts.CoreCloneClone.clone
  (self : uapi.binder_object_header) : Result uapi.binder_object_header := do
  ok self

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_object_header}]
    Source: 'src/lib.rs', lines 42:19-42:24 -/
@[reducible]
def uapi.binder_object_header.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_object_header := {
  clone := uapi.binder_object_header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::marker::Copy for spike_binder_remodel::uapi::binder_object_header}]
    Source: 'src/lib.rs', lines 42:13-42:17 -/
@[reducible]
def uapi.binder_object_header.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_object_header := {
  cloneInst := uapi.binder_object_header.Insts.CoreCloneClone
}

/-- [spike_binder_remodel::uapi::flat_binder_object]
    Source: 'src/lib.rs', lines 49:4-54:5
    Visibility: public -/
structure uapi.flat_binder_object where
  hdr : uapi.binder_object_header
  flags : Std.U32
  __bindgen_anon_1 : Std.U64
  cookie : Std.U64

/-- [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::flat_binder_object}::clone]:
    Source: 'src/lib.rs', lines 48:19-48:24
    Visibility: public -/
def uapi.flat_binder_object.Insts.CoreCloneClone.clone
  (self : uapi.flat_binder_object) : Result uapi.flat_binder_object := do
  ok self

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::flat_binder_object}]
    Source: 'src/lib.rs', lines 48:19-48:24 -/
@[reducible]
def uapi.flat_binder_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.flat_binder_object := {
  clone := uapi.flat_binder_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::marker::Copy for spike_binder_remodel::uapi::flat_binder_object}]
    Source: 'src/lib.rs', lines 48:13-48:17 -/
@[reducible]
def uapi.flat_binder_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.flat_binder_object := {
  cloneInst := uapi.flat_binder_object.Insts.CoreCloneClone
}

/-- [spike_binder_remodel::uapi::binder_fd_object]
    Source: 'src/lib.rs', lines 58:4-63:5
    Visibility: public -/
structure uapi.binder_fd_object where
  hdr : uapi.binder_object_header
  pad_flags : Std.U32
  __bindgen_anon_1 : Std.U64
  cookie : Std.U64

/-- [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_fd_object}::clone]:
    Source: 'src/lib.rs', lines 57:19-57:24
    Visibility: public -/
def uapi.binder_fd_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_fd_object) : Result uapi.binder_fd_object := do
  ok self

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_fd_object}]
    Source: 'src/lib.rs', lines 57:19-57:24 -/
@[reducible]
def uapi.binder_fd_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_fd_object := {
  clone := uapi.binder_fd_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::marker::Copy for spike_binder_remodel::uapi::binder_fd_object}]
    Source: 'src/lib.rs', lines 57:13-57:17 -/
@[reducible]
def uapi.binder_fd_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_fd_object := {
  cloneInst := uapi.binder_fd_object.Insts.CoreCloneClone
}

/-- [spike_binder_remodel::uapi::binder_buffer_object]
    Source: 'src/lib.rs', lines 67:4-74:5
    Visibility: public -/
structure uapi.binder_buffer_object where
  hdr : uapi.binder_object_header
  flags : Std.U32
  buffer : Std.U64
  length : Std.U64
  parent : Std.U64
  parent_offset : Std.U64

/-- [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_buffer_object}::clone]:
    Source: 'src/lib.rs', lines 66:19-66:24
    Visibility: public -/
def uapi.binder_buffer_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_buffer_object) : Result uapi.binder_buffer_object := do
  ok self

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_buffer_object}]
    Source: 'src/lib.rs', lines 66:19-66:24 -/
@[reducible]
def uapi.binder_buffer_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_buffer_object := {
  clone := uapi.binder_buffer_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::marker::Copy for spike_binder_remodel::uapi::binder_buffer_object}]
    Source: 'src/lib.rs', lines 66:13-66:17 -/
@[reducible]
def uapi.binder_buffer_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_buffer_object := {
  cloneInst := uapi.binder_buffer_object.Insts.CoreCloneClone
}

/-- [spike_binder_remodel::uapi::binder_fd_array_object]
    Source: 'src/lib.rs', lines 78:4-84:5
    Visibility: public -/
structure uapi.binder_fd_array_object where
  hdr : uapi.binder_object_header
  pad : Std.U32
  num_fds : Std.U64
  parent : Std.U64
  parent_offset : Std.U64

/-- [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_fd_array_object}::clone]:
    Source: 'src/lib.rs', lines 77:19-77:24
    Visibility: public -/
def uapi.binder_fd_array_object.Insts.CoreCloneClone.clone
  (self : uapi.binder_fd_array_object) :
  Result uapi.binder_fd_array_object
  := do
  ok self

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::clone::Clone for spike_binder_remodel::uapi::binder_fd_array_object}]
    Source: 'src/lib.rs', lines 77:19-77:24 -/
@[reducible]
def uapi.binder_fd_array_object.Insts.CoreCloneClone : core.clone.Clone
  uapi.binder_fd_array_object := {
  clone := uapi.binder_fd_array_object.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [spike_binder_remodel::uapi::{impl core::marker::Copy for spike_binder_remodel::uapi::binder_fd_array_object}]
    Source: 'src/lib.rs', lines 77:13-77:17 -/
@[reducible]
def uapi.binder_fd_array_object.Insts.CoreMarkerCopy : core.marker.Copy
  uapi.binder_fd_array_object := {
  cloneInst := uapi.binder_fd_array_object.Insts.CoreCloneClone
}

/-- [spike_binder_remodel::BINDER_TYPE_BINDER]
    Source: 'src/lib.rs', lines 88:0-88:47
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_BINDER : Std.U32 := 1935813253#u32

/-- [spike_binder_remodel::BINDER_TYPE_WEAK_BINDER]
    Source: 'src/lib.rs', lines 89:0-89:52
    Visibility: public -/
@[global_simps, irreducible]
def BINDER_TYPE_WEAK_BINDER : Std.U32 := 2002922117#u32

/-- [spike_binder_remodel::BINDER_TYPE_HANDLE]
    Source: 'src/lib.rs', lines 90:0-90:47
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_HANDLE : Std.U32 := 1936206469#u32

/-- [spike_binder_remodel::BINDER_TYPE_WEAK_HANDLE]
    Source: 'src/lib.rs', lines 91:0-91:52
    Visibility: public -/
@[global_simps, irreducible]
def BINDER_TYPE_WEAK_HANDLE : Std.U32 := 2003315333#u32

/-- [spike_binder_remodel::BINDER_TYPE_FD]
    Source: 'src/lib.rs', lines 92:0-92:43
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_FD : Std.U32 := 1717840517#u32

/-- [spike_binder_remodel::BINDER_TYPE_FDA]
    Source: 'src/lib.rs', lines 93:0-93:44
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_FDA : Std.U32 := 1717854597#u32

/-- [spike_binder_remodel::BINDER_TYPE_PTR]
    Source: 'src/lib.rs', lines 94:0-94:44
    Visibility: public -/
@[global_simps, irreducible] def BINDER_TYPE_PTR : Std.U32 := 1886661253#u32

/-- [spike_binder_remodel::type_to_size]:
    Source: 'src/lib.rs', lines 97:0-108:1
    Visibility: public -/
def type_to_size (type_ : Std.U32) : Result (Option Std.Usize) := do
  match type_ with
  | 2002922117#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1935813253#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 2003315333#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1936206469#uscalar =>
    let i ← core.mem.size_of uapi.flat_binder_object
    ok (some i)
  | 1717840517#uscalar =>
    let i ← core.mem.size_of uapi.binder_fd_object
    ok (some i)
  | 1886661253#uscalar =>
    let i ← core.mem.size_of uapi.binder_buffer_object
    ok (some i)
  | 1717854597#uscalar =>
    let i ← core.mem.size_of uapi.binder_fd_array_object
    ok (some i)
  | _ => ok none

/-- [spike_binder_remodel::ptr_align]:
    Source: 'src/lib.rs', lines 110:0-113:1
    Visibility: public -/
def ptr_align (value : Std.Usize) : Result (Option Std.Usize) := do
  let i ← core.mem.size_of Std.Usize
  let size ← i - 1#usize
  let o ← lift (Usize.checked_add value size)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i1 ← lift (~~~ size)
    let i2 ← lift (val &&& i1)
    ok (some i2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.Usize residual

/-- [spike_binder_remodel::is_aligned]:
    Source: 'src/lib.rs', lines 115:0-117:1
    Visibility: public -/
def is_aligned (value : Std.Usize) (to1 : Std.Usize) : Result Bool := do
  let i ← value % to1
  ok (i = 0#usize)

/-- [spike_binder_remodel::size_check]:
    Source: 'src/lib.rs', lines 119:0-126:1
    Visibility: public -/
def size_check
  (offset : Std.Usize) (size : Std.Usize) (buffer_size : Std.Usize) :
  Result (core.result.Result Unit Error)
  := do
  let o ← lift (Usize.checked_add offset size)
  let overflow_fail := core.option.Option.is_none o
  let i ← lift (core.num.Usize.wrapping_add offset size)
  if overflow_fail
  then ok (core.result.Result.Err EINVAL)
  else
    if i > buffer_size
    then ok (core.result.Result.Err EINVAL)
    else ok (core.result.Result.Ok ())

/-- [spike_binder_remodel::SliceReader]
    Source: 'src/lib.rs', lines 129:0-132:1
    Visibility: public -/
structure SliceReader where
  data : Slice Std.U8
  pos : Std.Usize

/-- [spike_binder_remodel::{spike_binder_remodel::SliceReader<'a>}::new]:
    Source: 'src/lib.rs', lines 135:4-137:5
    Visibility: public -/
def SliceReader.new (data : Slice Std.U8) : Result SliceReader := do
  ok { data, pos := 0#usize }

/-- [spike_binder_remodel::{spike_binder_remodel::SliceReader<'a>}::len]:
    Source: 'src/lib.rs', lines 139:4-141:5 -/
def SliceReader.len (self : SliceReader) : Result Std.Usize := do
  let i := Slice.len self.data
  i - self.pos

/-- [spike_binder_remodel::{spike_binder_remodel::SliceReader<'a>}::clone_reader]:
    Source: 'src/lib.rs', lines 143:4-148:5 -/
def SliceReader.clone_reader (self : SliceReader) : Result SliceReader := do
  ok self

/-- [spike_binder_remodel::{spike_binder_remodel::SliceReader<'a>}::read_slice]:
    Source: 'src/lib.rs', lines 150:4-158:5 -/
def SliceReader.read_slice
  (self : SliceReader) (out : Slice Std.U8) :
  Result ((core.result.Result Unit Error) × SliceReader × (Slice Std.U8))
  := do
  let n := Slice.len out
  let i ← SliceReader.len self
  if n > i
  then ok (core.result.Result.Err EINVAL, self, out)
  else
    let i1 ← self.pos + n
    let s ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) self.data { start := self.pos, «end» := i1 }
    let out1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 out s
    ok (core.result.Result.Ok (), { self with pos := i1 }, out1)

/-- [spike_binder_remodel::{spike_binder_remodel::SliceReader<'a>}::skip]:
    Source: 'src/lib.rs', lines 160:4-166:5 -/
def SliceReader.skip
  (self : SliceReader) (n : Std.Usize) :
  Result ((core.result.Result Unit Error) × SliceReader)
  := do
  let i ← SliceReader.len self
  if n > i
  then ok (core.result.Result.Err EINVAL, self)
  else
    let i1 ← self.pos + n
    ok (core.result.Result.Ok (), { self with pos := i1 })

/-- [spike_binder_remodel::OBJECT_SIZE]
    Source: 'src/lib.rs', lines 179:0-179:34
    Visibility: public -/
@[global_simps, irreducible] def OBJECT_SIZE : Std.Usize := 40#usize

/-- [spike_binder_remodel::BinderObjectBytes]
    Source: 'src/lib.rs', lines 185:0-185:52
    Visibility: public -/
@[reducible]
def BinderObjectBytes := Array Std.U8 40#usize

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::hdr_type]:
    Source: 'src/lib.rs', lines 269:4-271:5
    Visibility: public -/
def BinderObjectBytes.hdr_type
  (self : BinderObjectBytes) : Result Std.U32 := do
  let i ← Array.index_usize self 0#usize
  let i1 ← Array.index_usize self 1#usize
  let i2 ← Array.index_usize self 2#usize
  let i3 ← Array.index_usize self 3#usize
  ok (core.num.U32.from_le_bytes (Array.make 4#usize [ i, i1, i2, i3 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::size]:
    Source: 'src/lib.rs', lines 250:4-260:5
    Visibility: public -/
def BinderObjectBytes.size (self : BinderObjectBytes) : Result Std.Usize := do
  let i ← BinderObjectBytes.hdr_type self
  let o ← type_to_size i
  match o with
  | none => ok 0#usize
  | some n => ok n

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from_inner]:
    Source: 'src/lib.rs', lines 221:4-248:5
    Visibility: public -/
def BinderObjectBytes.read_from_inner
  {R : Type} (coreopsfunctionFnOnceRTupleArrayU840ResultArrayU840ErrorInst :
  core.ops.function.FnOnce R (Array Std.U8 40#usize) (core.result.Result (Array
  Std.U8 40#usize) Error)) (fill : R) :
  Result (core.result.Result BinderObjectBytes Error)
  := do
  let a := Array.repeat 40#usize 0#u8
  let r ←
    coreopsfunctionFnOnceRTupleArrayU840ResultArrayU840ErrorInst.call_once fill
      a
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let type_ ← BinderObjectBytes.hdr_type val
    let o ← type_to_size type_
    let b := core.option.Option.is_none o
    if b
    then ok (core.result.Result.Err EINVAL)
    else ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      BinderObjectBytes (core.convert.FromSame Error) residual

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from::closure]
    Source: 'src/lib.rs', lines 207:43-211:9 -/
@[reducible]
def BinderObjectBytes.read_from.closure := SliceReader

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from::{impl core::ops::function::FnOnce<([u8; 40usize],), core::result::Result<[u8; 40usize], spike_binder_remodel::Error>> for spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from::closure<'_0, '_1>}::call_once]:
    Source: 'src/lib.rs', lines 207:43-211:9 -/
def
  BinderObjectBytes.read_from.closure.Insts.CoreOpsFunctionFnOnceTupleArrayU840ResultArrayU840Error.call_once
  (c : BinderObjectBytes.read_from.closure)
  (tupled_args : Array Std.U8 40#usize) :
  Result (core.result.Result (Array Std.U8 40#usize) Error)
  := do
  let s ← lift (Array.to_slice tupled_args)
  let i := Slice.len s
  let i1 ← SliceReader.len c
  let read_len ← lift (core.cmp.impls.OrdUsize.min i i1)
  let sr ← SliceReader.clone_reader c
  let (s1, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) tupled_args
      { «end» := read_len }
  let (r, _, s2) ← SliceReader.read_slice sr s1
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let tupled_args1 := index_mut_back s2
    ok (core.result.Result.Ok tupled_args1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Array Std.U8 40#usize) (core.convert.FromSame Error) residual

/-- Trait implementation: [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from::{impl core::ops::function::FnOnce<([u8; 40usize],), core::result::Result<[u8; 40usize], spike_binder_remodel::Error>> for spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from::closure<'_0, '_1>}]
    Source: 'src/lib.rs', lines 207:43-211:9 -/
@[reducible]
def
  BinderObjectBytes.read_from.closure.Insts.CoreOpsFunctionFnOnceTupleArrayU840ResultArrayU840Error
  : core.ops.function.FnOnce BinderObjectBytes.read_from.closure (Array Std.U8
  40#usize) (core.result.Result (Array Std.U8 40#usize) Error) := {
  call_once :=
    BinderObjectBytes.read_from.closure.Insts.CoreOpsFunctionFnOnceTupleArrayU840ResultArrayU840Error.call_once
}

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::read_from]:
    Source: 'src/lib.rs', lines 206:4-218:5
    Visibility: public -/
def BinderObjectBytes.read_from
  (reader : SliceReader) :
  Result ((core.result.Result BinderObjectBytes Error) × SliceReader)
  := do
  let r ←
    BinderObjectBytes.read_from_inner
      BinderObjectBytes.read_from.closure.Insts.CoreOpsFunctionFnOnceTupleArrayU840ResultArrayU840Error
      reader
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← BinderObjectBytes.size val
    let (r1, reader1) ← SliceReader.skip reader i
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      ok (core.result.Result.Ok val, reader1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r2 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          BinderObjectBytes (core.convert.FromSame Error) residual
      ok (r2, reader1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        BinderObjectBytes (core.convert.FromSame Error) residual
    ok (r1, reader)

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fbo_flags]:
    Source: 'src/lib.rs', lines 274:4-276:5
    Visibility: public -/
def BinderObjectBytes.fbo_flags
  (self : BinderObjectBytes) : Result Std.U32 := do
  let i ← Array.index_usize self 4#usize
  let i1 ← Array.index_usize self 5#usize
  let i2 ← Array.index_usize self 6#usize
  let i3 ← Array.index_usize self 7#usize
  ok (core.num.U32.from_le_bytes (Array.make 4#usize [ i, i1, i2, i3 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fbo_binder]:
    Source: 'src/lib.rs', lines 278:4-280:5
    Visibility: public -/
def BinderObjectBytes.fbo_binder
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 8#usize
  let i1 ← Array.index_usize self 9#usize
  let i2 ← Array.index_usize self 10#usize
  let i3 ← Array.index_usize self 11#usize
  let i4 ← Array.index_usize self 12#usize
  let i5 ← Array.index_usize self 13#usize
  let i6 ← Array.index_usize self 14#usize
  let i7 ← Array.index_usize self 15#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fbo_handle]:
    Source: 'src/lib.rs', lines 282:4-284:5
    Visibility: public -/
def BinderObjectBytes.fbo_handle
  (self : BinderObjectBytes) : Result Std.U32 := do
  let i ← Array.index_usize self 8#usize
  let i1 ← Array.index_usize self 9#usize
  let i2 ← Array.index_usize self 10#usize
  let i3 ← Array.index_usize self 11#usize
  ok (core.num.U32.from_le_bytes (Array.make 4#usize [ i, i1, i2, i3 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fbo_cookie]:
    Source: 'src/lib.rs', lines 285:4-287:5
    Visibility: public -/
def BinderObjectBytes.fbo_cookie
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 16#usize
  let i1 ← Array.index_usize self 17#usize
  let i2 ← Array.index_usize self 18#usize
  let i3 ← Array.index_usize self 19#usize
  let i4 ← Array.index_usize self 20#usize
  let i5 ← Array.index_usize self 21#usize
  let i6 ← Array.index_usize self 22#usize
  let i7 ← Array.index_usize self 23#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fdo_fd]:
    Source: 'src/lib.rs', lines 291:4-293:5
    Visibility: public -/
def BinderObjectBytes.fdo_fd (self : BinderObjectBytes) : Result Std.U32 := do
  let i ← Array.index_usize self 8#usize
  let i1 ← Array.index_usize self 9#usize
  let i2 ← Array.index_usize self 10#usize
  let i3 ← Array.index_usize self 11#usize
  ok (core.num.U32.from_le_bytes (Array.make 4#usize [ i, i1, i2, i3 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fdo_cookie]:
    Source: 'src/lib.rs', lines 294:4-296:5
    Visibility: public -/
def BinderObjectBytes.fdo_cookie
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 16#usize
  let i1 ← Array.index_usize self 17#usize
  let i2 ← Array.index_usize self 18#usize
  let i3 ← Array.index_usize self 19#usize
  let i4 ← Array.index_usize self 20#usize
  let i5 ← Array.index_usize self 21#usize
  let i6 ← Array.index_usize self 22#usize
  let i7 ← Array.index_usize self 23#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::bbo_flags]:
    Source: 'src/lib.rs', lines 299:4-301:5
    Visibility: public -/
def BinderObjectBytes.bbo_flags
  (self : BinderObjectBytes) : Result Std.U32 := do
  let i ← Array.index_usize self 4#usize
  let i1 ← Array.index_usize self 5#usize
  let i2 ← Array.index_usize self 6#usize
  let i3 ← Array.index_usize self 7#usize
  ok (core.num.U32.from_le_bytes (Array.make 4#usize [ i, i1, i2, i3 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::bbo_buffer]:
    Source: 'src/lib.rs', lines 302:4-304:5
    Visibility: public -/
def BinderObjectBytes.bbo_buffer
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 8#usize
  let i1 ← Array.index_usize self 9#usize
  let i2 ← Array.index_usize self 10#usize
  let i3 ← Array.index_usize self 11#usize
  let i4 ← Array.index_usize self 12#usize
  let i5 ← Array.index_usize self 13#usize
  let i6 ← Array.index_usize self 14#usize
  let i7 ← Array.index_usize self 15#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::bbo_length]:
    Source: 'src/lib.rs', lines 305:4-307:5
    Visibility: public -/
def BinderObjectBytes.bbo_length
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 16#usize
  let i1 ← Array.index_usize self 17#usize
  let i2 ← Array.index_usize self 18#usize
  let i3 ← Array.index_usize self 19#usize
  let i4 ← Array.index_usize self 20#usize
  let i5 ← Array.index_usize self 21#usize
  let i6 ← Array.index_usize self 22#usize
  let i7 ← Array.index_usize self 23#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::bbo_parent]:
    Source: 'src/lib.rs', lines 308:4-310:5
    Visibility: public -/
def BinderObjectBytes.bbo_parent
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 24#usize
  let i1 ← Array.index_usize self 25#usize
  let i2 ← Array.index_usize self 26#usize
  let i3 ← Array.index_usize self 27#usize
  let i4 ← Array.index_usize self 28#usize
  let i5 ← Array.index_usize self 29#usize
  let i6 ← Array.index_usize self 30#usize
  let i7 ← Array.index_usize self 31#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::bbo_parent_offset]:
    Source: 'src/lib.rs', lines 311:4-313:5
    Visibility: public -/
def BinderObjectBytes.bbo_parent_offset
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 32#usize
  let i1 ← Array.index_usize self 33#usize
  let i2 ← Array.index_usize self 34#usize
  let i3 ← Array.index_usize self 35#usize
  let i4 ← Array.index_usize self 36#usize
  let i5 ← Array.index_usize self 37#usize
  let i6 ← Array.index_usize self 38#usize
  let i7 ← Array.index_usize self 39#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fdao_num_fds]:
    Source: 'src/lib.rs', lines 316:4-318:5
    Visibility: public -/
def BinderObjectBytes.fdao_num_fds
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 8#usize
  let i1 ← Array.index_usize self 9#usize
  let i2 ← Array.index_usize self 10#usize
  let i3 ← Array.index_usize self 11#usize
  let i4 ← Array.index_usize self 12#usize
  let i5 ← Array.index_usize self 13#usize
  let i6 ← Array.index_usize self 14#usize
  let i7 ← Array.index_usize self 15#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fdao_parent]:
    Source: 'src/lib.rs', lines 319:4-321:5
    Visibility: public -/
def BinderObjectBytes.fdao_parent
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 16#usize
  let i1 ← Array.index_usize self 17#usize
  let i2 ← Array.index_usize self 18#usize
  let i3 ← Array.index_usize self 19#usize
  let i4 ← Array.index_usize self 20#usize
  let i5 ← Array.index_usize self 21#usize
  let i6 ← Array.index_usize self 22#usize
  let i7 ← Array.index_usize self 23#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::{spike_binder_remodel::BinderObjectBytes}::fdao_parent_offset]:
    Source: 'src/lib.rs', lines 322:4-324:5
    Visibility: public -/
def BinderObjectBytes.fdao_parent_offset
  (self : BinderObjectBytes) : Result Std.U64 := do
  let i ← Array.index_usize self 24#usize
  let i1 ← Array.index_usize self 25#usize
  let i2 ← Array.index_usize self 26#usize
  let i3 ← Array.index_usize self 27#usize
  let i4 ← Array.index_usize self 28#usize
  let i5 ← Array.index_usize self 29#usize
  let i6 ← Array.index_usize self 30#usize
  let i7 ← Array.index_usize self 31#usize
  ok (core.num.U64.from_le_bytes
    (Array.make 8#usize [ i, i1, i2, i3, i4, i5, i6, i7 ]))

/-- [spike_binder_remodel::parse_one]:
    Source: 'src/lib.rs', lines 328:0-332:1
    Visibility: public -/
def parse_one
  (bytes : Slice Std.U8) : Result (core.result.Result Std.Usize Error) := do
  let reader ← SliceReader.new bytes
  let (r, _) ← BinderObjectBytes.read_from reader
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← BinderObjectBytes.size val
    ok (core.result.Result.Ok i)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.Usize (core.convert.FromSame Error) residual

end spike_binder_remodel
